export const DEFAULT_ENDPOINT = 'https://api.siteline.ai/v1/intake/pageview';
export const DEFAULT_SDK_NAME = '@siteline/js';
export const DEFAULT_SDK_VERSION = '1.0.8';
export const DEFAULT_INTEGRATION_TYPE = 'js';

export const LIMITS = {
  URL_MAX_LENGTH: 2048,
  METHOD_MAX_LENGTH: 10,
  USER_AGENT_MAX_LENGTH: 512,
  REF_MAX_LENGTH: 2048,
  IP_MAX_LENGTH: 45,
  ACCEPT_HEADER_MAX_LENGTH: 1024,
  INTEGRATION_TYPE_MAX_LENGTH: 50,
  SDK_MAX_LENGTH: 50,
  SDK_VERSION_MAX_LENGTH: 20,
  STATUS_MIN: 0,
  STATUS_MAX: 999,
  DURATION_MIN: 0,
  DURATION_MAX: 300000,
  MCP_METHOD_MAX_LENGTH: 100,
  MCP_TOOL_NAME_MAX_LENGTH: 256,
  MCP_CLIENT_NAME_MAX_LENGTH: 256,
  MCP_CLIENT_VERSION_MAX_LENGTH: 64,
  MCP_PROTOCOL_VERSION_MAX_LENGTH: 64,
  MCP_SESSION_ID_MAX_LENGTH: 256,
  MCP_AUTH_PRINCIPAL_HASH_MAX_LENGTH: 256,
  MCP_TRANSPORT_MAX_LENGTH: 64,
  MCP_JSONRPC_ERROR_CODE_MIN: -2147483648,
  MCP_JSONRPC_ERROR_CODE_MAX: 2147483647,
  MCP_RESPONSE_BYTES_MIN: 0,
  MCP_RESPONSE_BYTES_MAX: Number.MAX_SAFE_INTEGER,
  MCP_ARG_KEYS_MAX_ITEMS: 50,
  MCP_ARG_KEY_MAX_LENGTH: 128,
} as const;

export const TIMEOUT_MS = 5000;
